version: '3'

services:
  controlplane:
    build:
         context: ../../controlplane
         dockerfile: Dockerfile
    image: controlplane
    environment:
      - "GITHUB_TOKEN=${GITHUB_TOKEN}"
      - "GITHUB_ORG=${GITHUB_ORG}"
  runner:
    build:
      context: .
      dockerfile: runner.Dockerfile
    image: runner
    environment:
      - "GITHUB_ORG=${GITHUB_ORG}"
    deploy:
      replicas: 2
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.runner.env:/actions-runner/.env
